echo ib_ipoib >> /etc/modules
echo ib_umad >> /etc/modules
echo ib_ucm >> /etc/modules
echo ib_uverbs >> /etc/modules
echo rdma_ucm >> /etc/modules
echo rdma_cm >> /etc/modules
echo ib_cm >> /etc/modules
echo iw_cm >> /etc/modules
echo mlx4_ib >> /etc/modules
echo mlx4_en >> /etc/modules
